(() => {
  const P=window.TAMILANDA_PRODUCTS||[]; const AI=window.TamilandaAI; const WA=['919025478790','919363063571'];
  const state={q:'',cat:'All',sort:'Recommended',cart:{},smart:{step:1,audience:'Family',objective:'Balanced',budget:1000}};
  const $=id=>document.getElementById(id); const money=n=>'₹'+Math.round(Number(n)||0).toLocaleString('en-IN');
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const groups=['All','Crackers','Fountains','Sparklers','Sky Shots']; const more=['Chakkars','Kids','Other'];
  function sync(){const c=Object.values(state.cart).reduce((a,b)=>a+b,0);$('navCount').textContent=c;$('floatCount').textContent=c}
  function pills(){ $('pills').innerHTML=groups.map(x=>`<button class="pill ${state.cat===x?'active':''}" data-c="${x}">${x}</button>`).join(''); $('pills').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.cat=b.dataset.c;moreMenu(false);pills();render()}); $('moreMenu').innerHTML=more.map(x=>`<button data-c="${x}">${x}</button>`).join('');$('moreMenu').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.cat=b.dataset.c;moreMenu(false);render()}) }
  function moreMenu(v){$('moreMenu').classList.toggle('show',v??!$('moreMenu').classList.contains('show'))}
  function matches(p){const q=state.q.trim().toLowerCase();return (!q||[p.name,p.category,p.sourceCategory,p.pack].join(' ').toLowerCase().includes(q))&&(state.cat==='All'||AI.group(p)===state.cat)}
  function render(){let a=P.filter(matches);if(state.sort==='Price: Low → High')a.sort((x,y)=>x.price-y.price);if(state.sort==='Price: High → Low')a.sort((x,y)=>y.price-x.price);if(state.sort==='Biggest Saving')a.sort((x,y)=>y.savings-x.savings);if(state.sort==='Name A → Z')a.sort((x,y)=>x.name.localeCompare(y.name));$('meta').innerHTML=`<strong>${a.length}</strong> products`;$('grid').innerHTML=a.length?a.map(card).join(''):`<div class="empty">No products found.<br><br>Try another search or category.</div>`;Object.keys(state.cart).forEach(syncCard);}
  function card(p){const d=Math.round(p.discount),q=state.cart[p.id]||0;return `<article class="card ${q?'incart':''}" data-id="${p.id}"><div class="art">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none'">`:''}<div class="fallback">✦</div><span class="discount">-${d}%</span></div><div class="body"><div class="tag">${esc(AI.group(p))}</div><h3>${esc(p.name)}</h3><div class="pack">${esc(p.pack||'1 pack')}</div><div class="prices"><span class="mrp">${money(p.mrp)}</span><span class="offer">${money(p.price)}</span></div><button class="add" onclick="TamilandaApp.add(${p.id})">ADD TO CART <span>＋</span></button><div class="qty"><button onclick="TamilandaApp.chg(${p.id},-1)">−</button><strong>${q}</strong><button onclick="TamilandaApp.chg(${p.id},1)">＋</button></div></div></article>`}
  function syncCard(id){const c=document.querySelector(`.card[data-id="${id}"]`);if(!c)return;const q=state.cart[id]||0;c.classList.toggle('incart',q>0);const b=c.querySelector('.qty strong');if(b)b.textContent=q}
  function add(id){state.cart[id]=(state.cart[id]||0)+1;syncCard(id);sync()}
  function chg(id,d){state.cart[id]=(state.cart[id]||0)+d;if(state.cart[id]<=0)delete state.cart[id];syncCard(id);sync();if($('modalOverlay').style.display==='flex')drawCart()}
  function openSmart(){state.smart={step:1,audience:'Family',objective:'Balanced',budget:1000};drawSmart()}
  function closeModal(){$('modalOverlay').style.display='none'}
  function drawSmart(){const s=state.smart;let inner='';if(s.step===1)inner=stepAudience();else if(s.step===2)inner=stepObjective();else if(s.step===3)inner=stepBudget();else inner=stepResult();$('modalOverlay').style.display='flex';$('modalOverlay').innerHTML=`<div class="modal"><div class="modalHead"><div><span class="smartBadge">✦ SMART SUGGEST AI</span><h2>${s.step===4?'Your Personal Diwali Plan':'Build Your Diwali Plan'}</h2></div><button class="close" onclick="TamilandaApp.closeModal()">×</button></div><div class="progress">${[1,2,3,4].map(i=>`<i class="${i<=s.step?'on':''}"></i>`).join('')}</div>${inner}</div>`}
  function stepAudience(){const opts=[['Family','Balanced mix for home and everyone'],['Kids','Colourful, fun and lighter sound emphasis'],['Adults','More sound, larger effects and display'],['Everyone','Broad mix for different people']];return `<div class="qTitle">Who are you buying for?</div><div class="choices">${opts.map(x=>`<button class="choice ${state.smart.audience===x[0]?'active':''}" onclick="TamilandaApp.pick('audience','${x[0]}')"><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('')}</div><div class="modalActions"><span></span><button class="next" onclick="TamilandaApp.next()">Continue →</button></div>`}
  function stepObjective(){const opts=[['Balanced','A sensible mix across the major categories'],['Multipurpose','Sound + colour + family + display'],['Maximum Variety','More types, fewer quantities'],['More Sound','Push the selection toward sound crackers'],['More Colour','Push the selection toward visual effects'],['Premium','Higher-value display pieces'],['Budget Friendly','Stretch the budget across more affordable items']];return `<div class="qTitle">What kind of celebration do you want?</div><div class="choices">${opts.map(x=>`<button class="choice ${state.smart.objective===x[0]?'active':''}" onclick="TamilandaApp.pick('objective','${x[0]}')"><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('')}</div><div class="modalActions"><button class="back" onclick="TamilandaApp.prev()">← Back</button><button class="next" onclick="TamilandaApp.next()">Continue →</button></div>`}
  function stepBudget(){return `<div class="qTitle">What is your total budget?</div><input class="budgetInput" id="budgetInput" type="number" min="100" step="50" value="${state.smart.budget}"><div class="budgetChips">${[500,1000,1500,2000,3000,5000].map(v=>`<button class="budgetChip ${state.smart.budget===v?'active':''}" onclick="TamilandaApp.setBudget(${v})">₹${v.toLocaleString('en-IN')}</button>`).join('')}</div><div class="note"><b>AI planning rule:</b> the recommendation stays inside your budget, deliberately spreads the spend across categories, and adjusts quantity/value based on your audience and objective. It will never silently exceed the budget.</div><div class="modalActions"><button class="back" onclick="TamilandaApp.prev()">← Back</button><button class="next" onclick="TamilandaApp.build()">Build My Selection ✦</button></div>`}
  function stepResult(){const r=AI.recommend(state.smart),s=state.smart;const reason=s.audience==='Kids'?'I reduced sound-heavy emphasis and prioritised colour, sparklers, fountains and kid-suitable novelty items.':s.audience==='Adults'?'I increased the weight of sound, crackers, larger effects and display items.':s.audience==='Family'?'I balanced categories so one person does not get a full cart of the same type.':'I kept the selection varied so different people can find something they enjoy.';const objective=s.objective==='Multipurpose'?'This covers multiple experiences rather than overloading one category.':s.objective==='Maximum Variety'?'This spreads the budget across more types with smaller quantities.':s.objective==='More Sound'?'This selection is intentionally sound-led.':s.objective==='More Colour'?'This selection is intentionally visual-effect-led.':s.objective==='Premium'?'This selection leans toward premium display items while staying affordable.':s.objective==='Budget Friendly'?'This selection uses lower-price items to stretch the budget.':'This selection keeps a balanced mix.';return `<div class="reasons"><strong>${esc(s.audience)} • ${esc(s.objective)} • ${money(r.budget)} budget</strong><p>${reason} ${objective}</p><div class="tokenRow">${r.groups.map(g=>`<span class="token">${esc(g)}</span>`).join('')}</div></div><div class="recommendList">${r.items.map(p=>`<div class="recommendItem"><div><div class="recommendName">${esc(p.name)}</div><div class="recommendMeta">${esc(AI.group(p))} • ${esc(p.pack||'1 pack')}</div></div><div class="recommendPrice">${money(p.price)}</div></div>`).join('')}</div><div class="summary"><span>Recommended Total</span><strong>${money(r.total)}</strong></div><div class="miniExplain">${Math.round((r.total/r.budget)*100)}% of budget used • ${r.items.length} products • ${r.groups.length} categories covered • never exceeds your entered budget.</div><div class="modalActions"><button class="back" onclick="TamilandaApp.prev()">← Adjust</button><button class="next" onclick="TamilandaApp.addRecommendation()">Add All to Cart →</button></div>`}
  function drawCart(){const items=Object.entries(state.cart).map(([id,q])=>({p:P.find(x=>x.id==id),q})).filter(x=>x.p);const total=items.reduce((s,x)=>s+x.p.price*x.q,0),mrp=items.reduce((s,x)=>s+x.p.mrp*x.q,0);$('modalOverlay').style.display='flex';$('modalOverlay').innerHTML=`<div class="modal"><div class="modalHead"><div><span class="smartBadge">✦ YOUR CART</span><h2>Diwali Order</h2></div><button class="close" onclick="TamilandaApp.closeModal()">×</button></div>${items.length?`<div class="cartList">${items.map(x=>`<div class="cartItem"><div><div class="cartName">${esc(x.p.name)}</div><div class="cartSub">${money(x.p.price)} × ${x.q} = ${money(x.p.price*x.q)}</div></div><div class="qctl"><button onclick="TamilandaApp.chg(${x.p.id},-1)">−</button><b>${x.q}</b><button onclick="TamilandaApp.chg(${x.p.id},1)">＋</button></div></div>`).join('')}</div><div class="cartTotal"><span>Grand Total</span><strong>${money(total)}</strong></div><div class="meta" style="margin-top:7px">You save ${money(mrp-total)} vs listed MRP.</div><button class="waMain" onclick="TamilandaApp.sendWA(0)">📲 ORDER ON WHATSAPP</button><div class="waChoices"><button onclick="TamilandaApp.sendWA(0)">90254 78790</button><button onclick="TamilandaApp.sendWA(1)">93630 63571</button></div><div class="helper">WhatsApp will receive the selected products, quantities and total. Final availability and delivery/collection details can be confirmed there.</div>`:'<div class="empty">Your cart is empty.<br><br>Add products or use Smart Suggest.</div>'}</div>`}
  function openCart(){drawCart()}
  function pick(k,v){state.smart[k]=v;drawSmart()}
  function setBudget(v){state.smart.budget=v;drawSmart()}
  function next(){if(state.smart.step<4){if(state.smart.step===3)state.smart.budget=Math.max(100,Number($('budgetInput').value)||1000);state.smart.step++;drawSmart()}}
  function prev(){state.smart.step=Math.max(1,state.smart.step-1);drawSmart()}
  function build(){state.smart.budget=Math.max(100,Number($('budgetInput').value)||1000);state.smart.step=4;drawSmart()}
  function addRecommendation(){const r=AI.recommend(state.smart);r.items.forEach(p=>{state.cart[p.id]=(state.cart[p.id]||0)+1});sync();closeModal();render();openCart()}
  function sendWA(which){const items=Object.entries(state.cart).map(([id,q])=>({p:P.find(x=>x.id==id),q})).filter(x=>x.p);if(!items.length)return;const total=items.reduce((s,x)=>s+x.p.price*x.q,0);let msg='*TAMILANDA CRACKERS — DIWALI 2026 ORDER*\\n\\n';msg+=items.map(x=>`• ${x.p.name} × ${x.q} — ${money(x.p.price*x.q)}`).join('\\n');msg+=`\\n\\n*GRAND TOTAL: ${money(total)}*\\n\\nPlease confirm availability.`;window.open('https://wa.me/'+WA[which]+'?text='+encodeURIComponent(msg),'_blank')}
  $('search').addEventListener('input',e=>{state.q=e.target.value;render()});$('sort').addEventListener('change',e=>{state.sort=e.target.value;render()});$('moreBtn').onclick=()=>moreMenu();$('smartOpen').onclick=openSmart;$('cartOpen').onclick=openCart;$('floatCart').onclick=openCart;
  pills();render();sync();
  window.TamilandaApp={add,chg,openSmart,closeModal,openCart,pick,setBudget,next,prev,build,addRecommendation,sendWA};
})();
